# Generated by Django 2.0.2 on 2018-02-21 17:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crawling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=10)),
                ('article_count', models.IntegerField(default=5)),
                ('naver_blog', models.TextField(null=True)),
                ('naver_news', models.TextField(null=True)),
                ('naver_cafe', models.TextField(null=True)),
                ('daum_blog', models.TextField(null=True)),
                ('daum_web', models.TextField(null=True)),
                ('daum_cafe', models.TextField(null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
